/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CafeInventory;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author honghao97
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /2);
        int y = (int) ((screen.getHeight() -getHeight()) /2);
        setLocation(x, y); 
        
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        Login = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        label4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        label4.setName(""); // NOI18N
        label4.setText("LOGIN SYSTEM");
        jPanel1.add(label4);
        label4.setBounds(200, 50, 270, 40);

        label5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label5.setText("USERNAME");
        jPanel1.add(label5);
        label5.setBounds(170, 160, 110, 20);

        label6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label6.setText("PASSWORD");
        jPanel1.add(label6);
        label6.setBounds(170, 220, 110, 20);

        textField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(textField3);
        textField3.setBounds(330, 150, 220, 30);

        Login.setActionCommand("Login");
        Login.setBackground(new java.awt.Color(102, 204, 255));
        Login.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Login.setLabel("Login");
        Login.setName("Login"); // NOI18N
        jPanel1.add(Login);
        Login.setBounds(290, 290, 70, 40);
        Login.getAccessibleContext().setAccessibleName("Login");

        button2.setBackground(new java.awt.Color(102, 204, 255));
        button2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        button2.setLabel("Reset");
        jPanel1.add(button2);
        button2.setBounds(120, 290, 70, 40);

        button3.setBackground(new java.awt.Color(102, 204, 255));
        button3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        button3.setLabel("Exit");
        jPanel1.add(button3);
        button3.setBounds(460, 290, 70, 40);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(330, 220, 220, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/coffee_login.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 419);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Login;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
