/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CafeInventory.Views;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;

/**
 *
 * @author honghao97
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();

        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) / 2);
        int y = (int) ((screen.getHeight() - getHeight()) / 2);
        setLocation(x, y);

    }
    
    public String getUsername() {
        return NameInput.getText();
    }
    
    public void setUsername(String text) {
        NameInput.setText(text);
    }
    
    public String getPassword() {
        return String.valueOf(PassInput.getPassword());
    }
    
    public void setPassword(String text) {
        PassInput.setText(text);
    }
    
    public void addExitActionListener(ActionListener a) {
        Exit.addActionListener(a);
    }
    
    public void addLoginActionListener(ActionListener a) {
        Login.addActionListener(a);
    }
    
    public void addResetActionListener(ActionListener a) {
        Reset.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginSystem = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        NameInput = new java.awt.TextField();
        PassInput = new javax.swing.JPasswordField();
        Exit = new java.awt.Button();
        Reset = new java.awt.Button();
        Login = new java.awt.Button();
        BackgroundPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        LoginSystem.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LoginSystem.setForeground(new java.awt.Color(255, 255, 255));
        LoginSystem.setText("LOGIN SYSTEM");
        jPanel1.add(LoginSystem);
        LoginSystem.setBounds(310, 50, 278, 44);

        Username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 102, 102));
        Username.setText("USERNAME");
        jPanel1.add(Username);
        Username.setBounds(260, 150, 101, 30);

        Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 102, 102));
        Password.setText("PASSWORD");
        jPanel1.add(Password);
        Password.setBounds(260, 210, 106, 22);

        NameInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NameInput.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(NameInput);
        NameInput.setBounds(380, 150, 200, 30);
        jPanel1.add(PassInput);
        PassInput.setBounds(380, 200, 200, 30);

        Exit.setBackground(new java.awt.Color(102, 204, 255));
        Exit.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Exit.setLabel("Exit");
        jPanel1.add(Exit);
        Exit.setBounds(470, 320, 70, 30);

        Reset.setBackground(new java.awt.Color(102, 204, 255));
        Reset.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Reset.setLabel("Reset");
        jPanel1.add(Reset);
        Reset.setBounds(360, 320, 64, 30);

        Login.setActionCommand("Login");
        Login.setBackground(new java.awt.Color(102, 204, 255));
        Login.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        Login.setLabel("Login");
        Login.setName("Login"); // NOI18N
        jPanel1.add(Login);
        Login.setBounds(250, 320, 64, 30);

        BackgroundPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackgroundPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CafeInventory/Resource/coffee_login.jpg"))); // NOI18N
        BackgroundPicture.setAlignmentX(0.5F);
        jPanel1.add(BackgroundPicture);
        BackgroundPicture.setBounds(0, 0, 650, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundPicture;
    private java.awt.Button Exit;
    private java.awt.Button Login;
    private javax.swing.JLabel LoginSystem;
    private java.awt.TextField NameInput;
    private javax.swing.JPasswordField PassInput;
    private javax.swing.JLabel Password;
    private java.awt.Button Reset;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
